[package]
name = "calculosalariodia"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.6"
tokio = { version = "1.33", features = ["full"] }
hyper = "0.14"
tower = "0.4"
serde = { version = "1.0", features = ["derive"] }